language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: oREd+qKW2tPsLTshe7axLTJZEgKBcO6EfjSbZMcBwyvCuWqYhELcbJsL6/sKah7xnDXaNgC3/cNZskmXYlGb/nFjgQBHhAoa9eTEKZBr5IgPmg9h+uUZvXfs9qJ/cx65CoaegY8pIFri2ikHkEcEoxuUgmjPqwYJRpd7I8hVk+w7KZ5J9iWu7NPWU1iDDsQ1S4bhlhf9jzNtvcswTig8GdvZShnGwSdEVxDG5j67NhwO9zMKg+v3H7CAq8GS5ppVVkkxA02IReqjK9/uxELazxFek5PMhCfOVGO/BJOwtouVxO37PnMgg93k+Wn3huflRRdWNNqO2dp1C/ihWGd1IkVKvLMh5l01mxhyOkUObYwEs/MgOWIrim07fUOdWZDRNRrhUbJMmx+JZI6Tdh4vyZYFKHiY4LvN1vMhlM9NybpqgmGE68U9AVfCPyNto7xFSyxEY2IYJ7fazMVRxUhVSzZ5QGHkESB6DLHJD3ZudKJTJdf8Y5vCdAUAVP4/U45a35lGu8CMUE+i5dpTYQiGEbPEFZ1sMKHJYKz+reyiGNPBLCKlHr2VF41OkchlLmqqlINf+D6Gnwz/fIu44wAm3NIQQLdqaLkiXB7xSassrk//svXQyIE3TSXeasKSyKEpudo4BAKfJEGfikUfM55hLzOUZbbQibU6NHyov84QsLc=
  app: ipa-learning-backend
  on:
    repo: amyspeed/IPA-Back-End
  skip_cleanup: 'true'
